name: Deploy to launchpad.net

on:
  push:
    branches: 'ubuntu-impish-*'

jobs:
  build:
    name: Packaging software
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}

    - name: Trust key
      run: |
        gpg --no-tty --command-fd 0 --edit-key ${{ secrets.GPG_KEY_ID }} <<EOTRUST
        trust
        5
        y
        quit
        EOTRUST

    - name: List keys
      run: gpg -K

    - name: Run install commands
      run: |
        sudo apt-get install dput
        sudo apt-get install devscripts

    - name: Packaging software
      run: |
        cd $GITHUB_WORKSPACE
        mkdir debian
        mkdir debian/source

        cp install.sh debian/postinst

        echo "3.0 (native)" >> debian/source/format
        echo "10" >> debian/compat

        cat <<EOT >> debian/control
        Source: automysqlbackup
        Maintainer: sixshop <sixshop@github.com>
        Section: utils
        Priority: important
        Build-Depends: debhelper (>= 10)
        Standards-Version: 4.5.1

        Package: automysqlbackup
        Architecture: any
        Homepage: https://github.com/sixshop/automysqlbackup
        Description: A fork and further development of AutoMySQLBackup from sourceforge.
        EOT

    - name: Creating changelog
      run: |
        cat <<EOT >> debian/rules
        #!/usr/bin/make -f

        %:
                dh $@
        EOT

        echo -e "automysqlbackup ($(echo $GITHUB_REF | grep -oP "([0-9].*)")) $(echo $GITHUB_REF | grep -oP "(?<=\-).*(?=\-)"); urgency=medium\n" >> debian/changelog
        echo -e "  * ${{ github.event.head_commit.message }}\n" >> debian/changelog
        echo " -- ${{ secrets.GPG_OWNER }}  $(date +'%a, %d %b %Y %T %z')" >> debian/changelog

        cat debian/changelog

    - name: Building AutoMySQLBackup
      run: debuild -S -sa

    - name: Publish to PPA
      run: ls ../
