name: Deploy to launchpad.net

on:
  push:
    branches: 'ubuntu-impish-*'

jobs:
  build:
    name: Packaging software
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v4
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: Run install commands
      run: |
        sudo apt-get install dput
        sudo apt-get install devscripts

    - name: Packaging software
      run: |
        cd $GITHUB_WORKSPACE
        mkdir debian
        mkdir debian/source

        cp install.sh debian/postinst

        echo "3.0 (native)" >> debian/source/format
        echo "10" >> debian/compat

        cat <<EOF >> debian/control
        Source: automysqlbackup
        Maintainer: sixshop <sixshop@github.com>
        Section: utils
        Priority: important
        Build-Depends: debhelper (>= 10)
        Standards-Version: 4.5.1

        Package: automysqlbackup
        Architecture: any
        Homepage: https://github.com/sixshop/automysqlbackup
        Description: A fork and further development of AutoMySQLBackup from sourceforge.
        EOF

    - name: Creating changelog
      run: |
        cat <<EOF >> debian/rules
        #!/usr/bin/make -f

        %:
                dh $@
        EOF

        cat <<EOF >> debian/changelog
        automysqlbackup ($(echo ${GITHUB_REF} | grep "([0-9].*)")) echo $GITHUB_REF | grep -oP "(?<=\-).*(?=\-)"; urgency=medium

          * ${{ github.event.head_commit.message }}

         -- ${{ secrets.GPG_OWNER }}  $(date +'%a, %d %b %Y %T %z')
        EOF

    - name: Building AutoMySQLBackup
      run: debuild -us -uc

    - name: Publish to PPA
      run: ls ../
